name: Inventory-app workflow

on: [push]

jobs:
  tests:
    name: PEP8 check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort mypy isort black
        pip install -r requirements.txt
    - name: Test with isort
      run: |
        python -m isort --diff --check core
    - name: Test with black
      run: |
        python -m black --diff --check core
    - name: Test with flake8
      run: |
        python -m flake8 core
    - name: Test with mypy
      run: |
        python -m mypy core    



